(define (merge loi1 loi2)
  (cond ((null? loi1) loi2)
        ((null? loi2) loi1)
        (else (let ((car_loi1 (car loi1))
                    (car_loi2 (car loi2)))
                  (if (< car_loi1 car_loi2)
                      (cons car_loi1 (merge (cdr loi1) loi2))
                      (cons car_loi2 (merge loi1 (cdr loi2))))))))
(merge '(1 4) '(1 2 8))
(merge '(35 62 81 90 91) '(3 83 85 90))